# Generated by Django 3.1.2 on 2020-10-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('link', models.URLField()),
                ('hashtags', models.CharField(max_length=200)),
                ('tweet_id', models.IntegerField()),
            ],
        ),
    ]
